version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/boilerplate-api
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    mode: 755
    type:
      - directory
hooks:
  ApplicationStop:
    - location: deregister_from_elb.sh
    - location: scripts/stop_server.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
    - location: scripts/register_with_elb.sh
      timeout: 180
      runas: ubuntu
